development:
  adapter: postgresql
  encoding: unicode
  database: inventory_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: inventory_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: inventory_production
  pool: 5
  username: postgres
  password:
