development:
  adapter: postgresql
  encoding: unicode
  database: kizai_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: kizai_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: kizai_production
  pool: 5
  username: postgres
  password:
